# Generated by Django 3.0.2 on 2020-02-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metro',
        ),
    ]
